build: fix CLI where readline headers aren't in default search path
-- Found Readline: /usr/local/include
-- Performing Test READLINE_NO_CURSES_TEST
-- Performing Test READLINE_NO_CURSES_TEST - Failed
-- readline test failed - some systems expect you to link with termcap or curses libraries
-- please find an example there: https://bugzilla.redhat.com/show_bug.cgi?id=499837
-- trying to find and link curses library...
-- Found Curses: /usr/lib/libcurses.so
-- Performing Test READLINE_CURSES_TEST
-- Performing Test READLINE_CURSES_TEST - Failed
CMake Warning at cli/CMakeLists.txt:46 (message):
  no readline library found, using stub

/usr/bin/cc  -DREADLINE_NO_CURSES_TEST -fPIE -o CMakeFiles/cmTC_2e5b8.dir/src.c.o   -c src.c
src.c:3:10: fatal error: 'readline/readline.h' file not found
 #include <readline/readline.h>
          ^~~~~~~~~~~~~~~~~~~~~

/usr/bin/c++  -DHAVE_LIBMAGIC -DMTPZ_ENABLED -DUSB_BACKEND_LIBUSB -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -I../ -I../mtp/backend/posix -I../mtp/backend/libusb -isystem ../cli/Readline_INCLUDE_DIR -O3 -DNDEBUG -fPIE   -Wall -pthread -std=gnu++11 -MD -MT cli/CMakeFiles/aft-mtp-cli.dir/CommandLine.cpp.o -MF cli/CMakeFiles/aft-mtp-cli.dir/CommandLine.cpp.o.d -o cli/CMakeFiles/aft-mtp-cli.dir/CommandLine.cpp.o -c ../cli/CommandLine.cpp
../cli/CommandLine.cpp:26:10: fatal error: 'readline/readline.h' file not found
 #include <readline/readline.h>
          ^~~~~~~~~~~~~~~~~~~~~