cli: add missing header found by GCC 4.9
In file included from cli/Session.cpp:22:0:
./cli/PosixStreams.h: In constructor 'cli::ObjectInputStream::ObjectInputStream(const string&)':
./cli/PosixStreams.h:72:18: error: 'perror' was not declared in this scope
     perror("open");
                  ^
./cli/PosixStreams.h: In constructor 'cli::ObjectOutputStream::ObjectOutputStream(const string&)':
./cli/PosixStreams.h:109:18: error: 'perror' was not declared in this scope
     perror("open");
                  ^